//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorDepot
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackDriver
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdDriver { get; set; }
        public string Feedback { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
