//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorDepot
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryClientDriver
    {
        public int Id { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IdRequestDriver { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> CountPeople { get; set; }
        public string Description { get; set; }

        public string VisibilityRevoke 
        { 
            get
            {
                if (DateTime.Now <= Data.Value)
                    return "Visibility";
                else
                    return "Collapsed";
            }
        }

        public string VisibilitySelect
        {
            get
            {
                if (DateTime.Now <= Data.Value)
                    return "Visibility";
                else
                    return "Collapsed";
            }
        }

        public virtual RequestDriver RequestDriver { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
