//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorDepot
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class RequestDriver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestDriver()
        {
            this.HistoryClientDriver = new HashSet<HistoryClientDriver>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string CountPeople { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> IdPlaceOfDeparture { get; set; }
        public Nullable<int> IdPlaceOfArrival { get; set; }
        public string Description { get; set; }

        public string VisibilityReverse
        {
            get
            {
                if (MainWindow.CurrentUser.Id == IdUser)
                    return "Collapsed";
                else
                    return "Visibility";
            }
        }

        public string VisibilityEdit
        {
            get
            {
                if (Data.Value < DateTime.Now)
                    return "Collapsed";
                else
                    return "Visibility";
            }
        }

        public virtual ICollection<HistoryClientDriver> HistoryClientDriverAccept
        {
            get
            {
                return DataAccess.GetHistoriesClientDriver().Where(a => a.RequestDriver.IdUser == MainWindow.CurrentUser.Id && a.IdStatus == 3 && a.IdRequestDriver == Id).ToList();
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryClientDriver> HistoryClientDriver { get; set; }
        public virtual PlaceArrival PlaceArrival { get; set; }
        public virtual PlaceDeparture PlaceDeparture { get; set; }
        public virtual User User { get; set; }
    }
}
