//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorDepot
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestClient
    {
        public int Id { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> CountPeople { get; set; }
        public Nullable<int> IdPlaceOfDeparture { get; set; }
        public Nullable<int> IdPlaceOfArrival { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Place Place { get; set; }
        public virtual Place Place1 { get; set; }
        public virtual User User { get; set; }
    }
}
